### ISSUE TITLE
Lack of module?

### ISSUE THREAD

**Issue by patw0929** [humanhighway/webpackLibExample#1]
Thanks for sharing webpack example project!

But when I clone the repo, and run the `gulp` command, there have some errors like:
- Cannot find module 'gulp-webpack'
- Module not found: Error: Cannot resolve module 'style'

Maybe it's lack of 'gulp-webpack' and 'style-loader' in `package.json` file?

``` diff
+    "gulp-webpack": "^0.3.0",
+    "style-loader": "^0.8.0",
```

**Comment by humanhighway** [comment]
hi @patw0929 :

Thanks YOU! fix soon!

Luc
